### ISSUE TITLE
Organization is None after creation

### ISSUE THREAD

**Issue by FrejaThoresen** [mlco2/codecarbon#757]
* CodeCarbon version: v2.8.2
* Python version: 3.12.8
* Operating System: Linux Ubuntu

### Description

After creating a config and following the prompts, an error of None. The error happens after I have already run 

```
carboncode login
```

and successfully logged in. 

### What I Did

```
codecarbon config
Welcome to CodeCarbon configuration wizard
Existing global config file found :
Current configuration : 

Config file content : 
{'api_endpoint': 'https://api.codecarbon.io'}
No organization_id in config, follow setup instruction to complete your 
configuration file!
? Use existing global ~/.codecarbon.config to configure or create a new file some
where else ? Create New Config
Creating new config file
Where do you want to put your config file ? [~/.codecarbon.config]: 
Config file created at /home/thoresen/.codecarbon.config
Current API endpoint is https://api.codecarbon.io. Press enter to continue or input other url [https://api.codecarbon.io]: 
? Pick existing organization from list or Create new organization ? Create New Or
ganization
Organization name [Code Carbon user test]: 
Organization description [Code Carbon user test]: 
[codecarbon ERROR @ 18:45:30] ApiClient Error when calling the API on https://api.codecarbon.io/organizations with : {"name": "Code Carbon user test", "description": "Code Carbon user test"}
[codecarbon ERROR @ 18:45:30] ApiClient API return http code 403 and answer : {"detail":"User not found"}
Created organization : None
╭────────────────────── Traceback (most recent call last) ──────────────────────╮
│ /home/thoresen/Code/green_ai_bench/.venv/lib/python3.12/site-packages/codecar │
│ bon/cli/main.py:217 in config                                                 │
│                                                                               │
│   214 │   │   print(f"Created organization : {organization}")                 │
│   215 │   else:                                                               │
│   216 │   │   organization = [orga for orga in organizations if orga["name"]  │
│ ❱ 217 │   org_id = organization["id"]                                         │
│   218 │   overwrite_local_config("organization_id", org_id, path=file_path)   │
│   219 │                                                                       │
│   220 │   projects = api.list_projects_from_organization(org_id)              │
│                                                                               │
│ ╭───────────────────────────────── locals ──────────────────────────────────╮ │
│ │                 api = <codecarbon.core.api_client.ApiClient object at     │ │
│ │                       0x7b18290c0440>                                     │ │
│ │        api_endpoint = 'https://api.codecarbon.io'                         │ │
│ │           file_path = PosixPath('/home/thoresen/.codecarbon.config')      │ │
│ │         global_path = PosixPath('/home/thoresen/.codecarbon.config')      │ │
│ │                home = PosixPath('/home/thoresen')                         │ │
│ │                 org = 'Create New Organization'                           │ │
│ │     org_description = 'Code Carbon user test'                             │ │
│ │            org_name = 'Code Carbon user test'                             │ │
│ │        organization = None                                                │ │
│ │ organization_create = OrganizationCreate(                                 │ │
│ │                       │   name='Code Carbon user test',                   │ │
│ │                       │   description='Code Carbon user test'             │ │
│ │                       )                                                   │ │
│ │       organizations = []                                                  │ │
│ │          use_config = 'Create New Config'                                 │ │
│ ╰───────────────────────────────────────────────────────────────────────────╯ │
╰───────────────────────────────────────────────────────────────────────────────╯
TypeError: 'NoneType' object is not subscriptable
```

**Comment by SaboniAmine** [comment]
Hello, 
Surprisingly, your applicative account hasn't been correctly created after you registered, meaning no default organization has been created. We need to instrumentate the signup process to understand what leads to this inconsistency.

In the mean time, it would be easier for us to remove your account, and let you try the registration process again. Would you mind if we do this ?

**Comment by FrejaThoresen** [comment]
Hello,
No problem, you can remove my account.

**Comment by Lux-aura** [comment]
Hi, 
I created my account as requested today. Then I followed the same script as FrejaThoresen did but on miniconda.
But I have the same issue. Could it be possible to help me to solve that ? 
Many thanks

**Comment by SaboniAmine** [comment]
Thanks for also reporting the issue. 
I have removed @FrejaThoresen's account, could you please try to sign up again ?
We have issues reproducing the bug, but currently trying to solve it, as it is not isolated. Sorry for the inconvenience.

**Comment by SaboniAmine** [comment]
The #763 PR should fix the login procedure from the CLI.
Apparently, we incorrectly assumed that every user would visit the dashboard before configuring the CLI to publish data, after login, were the default organization / projects would be created. The default behavior should be fixed in the next package release, thanks to your report.
By visiting https://dashboard.codecarbon.io/home, while logged in, @Lux-aura you should be able to use the CLI back again without having to wait the next release however.

**Comment by SaboniAmine** [comment]
This should be fixed with the `2.8.3` release. Could you please test again ?

**Comment by Lux-aura** [comment]
Hi, 
I tried this morning with the release. But the issue is still here. I'm sorry I probably forgot something.
I also create a new config file.  
For the organization creation, I tried : nothing (just click on Enter), my user name, random name... 
Please find the error in the image below : 

![Image](https://github.com/user-attachments/assets/525e6db0-34e3-429f-951f-d73672d34464)

**Comment by SaboniAmine** [comment]
Could you re-login first ?

**Comment by Lux-aura** [comment]
I relogged "successfully" before doing codecarbon config

**Comment by SaboniAmine** [comment]
Do you still have an error ? Can you share the your email you created your account with ?

**Comment by SaboniAmine** [comment]
That is weird, it seems that you are authenticated, with the feedback from the `codecarbon login` commande.
However, I see no account with the email you provided.

You should find a credentials.json file in the folder you are performing the auth. Could you please acknowledge that you have it, with a section with tokens, looking like : 
```
"tokens": {
    "access_token": "eyJhbGciOiJSUzI1N...,
    "id_token": "eyJhbGciOiJSUzI1N...",
    "token_type": "bearer",
    "expires_in": 86400,
    "refresh_token": "..."
  }
```

Also, an email field should be present (something like : `"email": "saboni.amine@gmail.com"`). 
Could you please report its value?

**Comment by Lux-aura** [comment]
I have it but with another email : lbs.lho@gmail.com (mine too)

The file : [credentials.json](https://github.com/user-attachments/files/18479545/credentials.json)

**Comment by SaboniAmine** [comment]
Thanks! Indeed, there seem to be a mismatch of accounts.
Please, remove your credentials.json file (and also, this can be used to authenticate you, so I would advise you not to publish it online. My request was unclear sorry, I just wanted to check your email).
I'll remove your account with the lbs.lho@gmail.com identifier, you should be able to recreate an account from scratch.

Here is the sequence : 
- I removed your old user account, which wasn't linked to an applicative account
- Remove your credentials.json & codecarbon.config file, make sure no copy is present in your current folder
- Once again, create an account either using the `codecarbon login` command or via the [dashboard](https://dashboard.codecarbon.io/home) (you must re-login from the CLI anyway after)
- run the config command

It then should be working correctly, with this reset

**Comment by Lux-aura** [comment]
I think that is not for me x) 
I'm truly sorry but still doesn't work. 

![Image](https://github.com/user-attachments/assets/b8178252-6667-41a0-bd15-5aa04a760332)

I don't know if it possible, but maybe doing a remote session could help ?

**Comment by SaboniAmine** [comment]
Sure, I'm sending you an email!

**Comment by SaboniAmine** [comment]
The fix is now correctly deployed, I'm closing this issue. Please re-open if you encounter it again, which shouldn't happen
